version: "3.2"
services:
  rabbitmq:
    image: rabbitmq:3.8-management-alpine
    container_name: 'rabbitmq'
    ports:
      - 15672:15672
      - 15692:15692

  redis:
    image: redis:6.2-alpine
    container_name: 'redis'
