version: 2.1

orbs:
  ruby: circleci/ruby@1.1

jobs:
  test:
    parallelism: 1
    parameters:
      ruby-image:
        type: string
    docker:
      - image: << parameters.ruby-image >>
    steps:
      - checkout
      - ruby/install-deps
      - run:
          name: Which bundler?
          command: bundle -v
      - ruby/rspec-test

# strangely, there seems to be very little documentation about exactly how martix builds work.
# By defining a param inside your job definition, Circle CI will automatically spawn a job for
# unique param value passed via `matrix`. Neat!
# https://circleci.com/blog/circleci-matrix-jobs/
workflows:
  build_and_test:
    jobs:
      - test:
          matrix:
            parameters:
              ruby-image:
                - circleci/ruby:2.5
                - circleci/ruby:2.6
                - circleci/ruby:2.7
                - circleci/jruby:9.1
                - circleci/jruby:9.2
